### ISSUE TITLE
For someone looking for PopOS systemd-boot solutions.

### ISSUE THREAD

**Issue by sNishant011** [ken-kuro/Zifriend-Keyboard-Linux#2]
I just copied the solution given in the readme file and with the help of chatgpt I could make it work.
The solution for POP OS:
```
sudo kernelstub -a "usbcore.quirks=5566:0008:gki"
```
where `5566` is `VendorID` and `0008` is `ProductId`.
Full conversation: https://chatgpt.com/share/3aa701a9-7b81-4fba-b974-7b29229bfb1f

**Comment by ken-kuro** [comment]
Thanks for the info, bro

**Comment by sNishant011** [comment]
Thanks to you as well for the detailed readme. 🎉
