### ISSUE TITLE
it didn’t worked boss 😭😭

### ISSUE THREAD

**Issue by Xlency** [ken-kuro/Zifriend-Keyboard-Linux#3]

**Comment by ken-kuro** [comment]
Hi there, can you add a little more detail, so I can try to help you :D

**Comment by Xlency** [comment]
after i followed your instructions i have done all things and the command you said, 
but after reboot my keyboard isn’t working like before,
(i use another keyboard to run the command)

**Comment by ken-kuro** [comment]
Might I know your keyboard name, and its VID + PID?  Also, can you use `sysctl -a` or `cat /proc/cmdline` to verify that you've correctly add the params for your system

**Comment by ken-kuro** [comment]
And fyi, this workaround only fix the problem with wired mode in Zifriend Keyboards (related to power management issue), so make sure your keyboard suit that description, and have trouble with wired mode only on Linux (should work fine with wireless mode, or in GRUB/Window,...)

**Comment by Xlency** [comment]
boss my keyboard model is Zifriend Za 63 and it is wired, 
the vid and pid is same as yours
5566:0008

**Comment by ken-kuro** [comment]
In that case could you please provide the output of the command I gave, or any other ways that we can check your kernel params

**Comment by Xlency** [comment]
![Screenshot_20240923_214104](https://github.com/user-attachments/assets/22874503-f9fc-4409-9f15-a37fa94170bb)
![Screenshot_20240923_213517](https://github.com/user-attachments/assets/afe2d646-cb76-4257-a1d0-9a367fb636ff)
i have done as you said
but it is not working boss please help me

**Comment by ken-kuro** [comment]
Oh, you added it in the wrong line bro

**Comment by ken-kuro** [comment]
It's the fifth white line, add the param after quiet splash

**Comment by ken-kuro** [comment]
The line you added is just a comment, it starts with # as you can see yourself

**Comment by Xlency** [comment]
can you tell me in more details, actually i,m a begginer

**Comment by Xlency** [comment]
![Screenshot_20240923_214953](https://github.com/user-attachments/assets/07181a1a-0cb9-47ba-8e4a-3d182ed74267)
now okay??

**Comment by ken-kuro** [comment]
No delete the quote "

**Comment by ken-kuro** [comment]
It should be like "quiet splash usbcore...."

**Comment by Xlency** [comment]
ohho I've deleted quota splash 🙂

**Comment by Xlency** [comment]
but my keyboard worked 😍😍😍😍😍😍😍😍
take love from heart

**Comment by ken-kuro** [comment]
It doesn't really matter, you can search about it yourself ![Screenshot_2024-09-23-22-56-12-612_com.android.chrome.jpg](https://github.com/user-attachments/assets/e52f2916-b914-43c4-b10a-82ae8b8a0bf7)

**Comment by ken-kuro** [comment]
Is your keyboard working now?

**Comment by ken-kuro** [comment]
Happy to help, gonna close this issue then
> but my keyboard worked 😍😍😍😍😍😍😍😍
> take love from heart 
>

**Comment by Xlency** [comment]
yess boss 😍😍
i can't express my feelings to you but i think you can understand 😭😭
if there is any other platform to contact with you please share with me. 
thanks a lot, ❤️
