### ISSUE TITLE
not working on linux min cinnamon edition

### ISSUE THREAD

**Issue by Xlency** [ken-kuro/Zifriend-Keyboard-Linux#4]
boss i've tried but this time it did'nt working

**Comment by ken-kuro** [comment]
> boss i've tried but this time it did'nt working 

Hi there, sorry I haven't used Linux Mint for a very long time, but with a quick search, I believe it also uses GRUB, so the workaround should work fine. You can search for GRUB instructions on Mint, or try to get support from the forum as well. If I read it right, you should make your changes in /etc/default/grub.d/90.custom.cfg, then run the command in the image. I'll keep this issue open until you sort it out, Linux has a learning curve, but it will pay off, good luck.
![Screenshot_2024-09-26-07-34-57-533_com.android.chrome.jpg](https://github.com/user-attachments/assets/9c00940a-27f6-4ba6-b57b-7a704711020e)

**Comment by Xlency** [comment]
okay boss, i will try this and then inform you 🫡

**Comment by ken-kuro** [comment]
Fyi, you can use `sysctl -a` or `cat /proc/cmdline` to verify the kernel params to see if it's working correctly, all the best!

**Comment by Xlency** [comment]
my problem fixed, but i don’t know using which formula
